#定义对象/Map集合
#user:
#  name: Tom
#  gender: male
#  age: 18
#
#
##定义数组/List/Set集合
#hobby:
#  - Java
#  - Game
#  - Sport
#注意值为0开头时，需加引号，否则会被识别为八进制
spring:
  application:
    name: springboot-mybatis-quickstart
  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/web01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ymn20035240

#mybatis配置
mybatis:
  configuration:
    #显示sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl